/* eslint-disable @typescript-eslint/no-explicit-any */
// next-env-overrides.d.ts
//
// Shim to cover next@16.2.6 published on npm without type declaration files.
//
// Confirmed bug: the files array in next package.json declares index.d.ts,
// dist/server/next.d.ts, etc., but none of those d.ts files are physically
// present in the official tgz on npmjs.org (tarball listing: 0 d.ts files,
// only js files). As a result, tsc --noEmit reports TS7016 "Could not find
// a declaration file for module next" errors in files generated by Next
// itself (next.config.ts, src/app/layout.tsx and the .next/types/ts files
// that Next regenerates in dev mode).
//
// at-types/next has been deprecated since 2019 (the latest published
// version is a stub whose readme says: "next provides its own type
// definitions, so you do not need at-types/next installed"), and the
// pre-stub versions (8.x) target Next 7/8 and are incompatible with
// Next 16. Therefore DefinitelyTyped cannot be used as a fallback.
//
// WORKAROUND: this file declares the modules that next@16.2.6 is missing,
// exposing the minimum symbols needed for tsc to resolve without resorting
// to a global any. At runtime everything works because the corresponding
// js file IS present in the tarball (only the d.ts files are missing).
//
// When the Next team publishes a patch of 16.2.x with the d.ts files
// restored in the npm tarball, this file can be removed without touching
// the project source code. Until then, do not hand edit it: if tsc starts
// complaining about a new module under next/dist/..., add the corresponding
// declaration following the same pattern.

// next main (package.json main: ./dist/server/next.js).
declare module "next" {
  const Next: any;
  export default Next;
  export type NextConfig = Record<string, unknown> | ((config: Record<string, unknown>) => Record<string, unknown>);
  export interface Metadata {
    title?: string | { default: string; template?: string | null };
    description?: string;
    applicationName?: string;
    generator?: string;
    referrer?: string;
    keywords?: string | string[];
    authors?: Array<{ name?: string; url?: string } | string>;
    creator?: string | { name?: string; url?: string };
    publisher?: string;
    icons?: string | Array<{ url: string; type?: string; sizes?: string }> | { icon?: unknown; apple?: unknown; other?: unknown };
    manifest?: string;
    themeColor?: string | Array<{ media: string; color: string }>;
    colorScheme?: "normal" | "dark" | "light" | "only light" | "only dark";
    viewport?: string | { width?: string | number; height?: string | number; initialScale?: number; maximumScale?: number; userScalable?: boolean };
    robots?: string | { index?: boolean; follow?: boolean; noarchive?: boolean; nosnippet?: boolean; noimageindex?: boolean };
    openGraph?: {
      title?: string;
      description?: string;
      url?: string;
      siteName?: string;
      type?: string;
      images?: Array<{ url: string; width?: number; height?: number; alt?: string }>;
      videos?: Array<{ url: string }>;
      audio?: Array<{ url: string }>;
    };
    twitter?: {
      card?: string;
      title?: string;
      description?: string;
      site?: string;
      creator?: string;
      images?: Array<{ url: string; alt?: string }>;
    };
    verification?: { google?: string; yahoo?: string; yandex?: string; me?: string[]; other?: Record<string, string> };
    other?: Record<string, string | string[]>;
    alternates?: { canonical?: string; languages?: Record<string, string>; media?: Record<string, string> };
    [key: string]: unknown;
  }
  export const Viewport: any;
  export const generateViewport: any;
  export const generateMetadata: any;
}

// next/font/google - used by src/app/layout.tsx for web fonts.
declare module "next/font/google" {
  interface FontConfig {
    src?: string;
    weight?: string | number | Array<string | number>;
    style?: string;
    subsets?: string[];
    variable?: string;
    preload?: boolean;
    display?: "auto" | "block" | "swap" | "fallback" | "optional";
    fallback?: string[];
    adjustFontFallback?: boolean;
    [key: string]: unknown;
  }
  type FontFunction = (config: FontConfig) => {
    className: string;
    variable: string;
    style: { fontFamily: string };
  };
  const font: FontFunction;
  export default font;
  // Named exports por cada Google Font (Inter, JetBrains_Mono, Roboto, etc.).
  // Declaramos los que usa el proyecto y dejamos un fallback any via index
  // signature para que tsc no se queje de otros nombres de fuentes.
  export const Inter: FontFunction;
  export const JetBrains_Mono: FontFunction;
  export const Roboto: FontFunction;
  export const Sarabun: FontFunction;
  // cualquier otra fuente Google: permite imports nombrados arbitrarios.
  // NOTA: TypeScript no permite index signatures en exports nombrados de
  // modules, asi que para fuentes nuevas hace falta agregarlas aqui.
}

// alias next/font (some imports use the barrel without subpath).
declare module "next/font" {
  const font: any;
  export default font;
}

// next/types.js - referenced by .next/types/validator.ts that the Next dev
// server regenerates on each boot.
declare module "next/types.js" {
  export type GetServerSidePropsContext = any;
  export type GetStaticPropsContext = any;
  export const NEXT_TYPE_CUSTOM_ROUTER: symbol;
}

// subpaths under next/dist referenced by .next/types/app/ts files generated
// by the Next TS plugin.
declare module "next/dist/lib/metadata/types/metadata-interface.js" {
  export interface Metadata {
    [key: string]: unknown;
  }
}

declare module "next/dist/build/segment-config/app/app-segment-config.js" {
  export type SegmentConfig = Record<string, unknown>;
  export interface PageSegmentConfig {
    generateStaticParams?: boolean;
    dynamic?: "auto" | "force-dynamic" | "error" | "force-static";
    revalidate?: number | false | null;
    fetchCache?: "auto" | "force-no-store" | "only-no-store" | "default-no-store" | "default-cache" | "only-cache" | "force-cache";
    runtime?: "nodejs" | "edge";
    preferredRegion?: string | string[];
    maxDuration?: number;
  }
}

// next/dist/server/next.js - package.json main entry, default export.
declare module "next/dist/server/next.js" {
  const NextServer: any;
  export default NextServer;
}
